import request from './request'

export const getEnterpriseDashboard = () => request.get('/enterprise/dashboard')
export const getOrganization = () => request.get('/enterprise/organization')
export const getOrganizations = () => request.get('/enterprise/organizations')
export const activateOrganization = (id) => request.post(`/enterprise/organizations/${id}/activate`)
export const addMember = (payload) => request.post('/enterprise/members', payload)
export const updateMember = (id, payload) => request.put(`/enterprise/members/${id}`, payload)
export const removeMember = (id) => request.delete(`/enterprise/members/${id}`)
export const getAuditLogs = () => request.get('/enterprise/audit-logs')
export const getApiKeys = () => request.get('/enterprise/api-keys')
export const createApiKey = (payload) => request.post('/enterprise/api-keys', payload)
export const revokeApiKey = (id) => request.delete(`/enterprise/api-keys/${id}`)
export const getWebhooks = () => request.get('/enterprise/webhooks')
export const createWebhook = (payload) => request.post('/enterprise/webhooks', payload)
export const deleteWebhook = (id) => request.delete(`/enterprise/webhooks/${id}`)
export const testWebhook = (id) => request.post(`/enterprise/webhooks/${id}/test`)
export const getWebhookDeliveries = () => request.get('/enterprise/webhook-deliveries')
export const getKnowledge = () => request.get('/enterprise/knowledge')
export const createKnowledge = (payload) => request.post('/enterprise/knowledge', payload)
export const addKnowledgeDocument = (id, documentId) => request.post(`/enterprise/knowledge/${id}/documents`, { document_id: documentId })
export const getKnowledgeDocuments = (id) => request.get(`/enterprise/knowledge/${id}/documents`)
export const searchKnowledge = (id, query, limit = 10) => request.get(`/enterprise/knowledge/${id}/search`, { params: { query, limit } })
export const getKnowledgeGraph = (id) => request.get(`/enterprise/knowledge/${id}/graph`)
export const getSchedules = () => request.get('/enterprise/schedules')
export const createSchedule = (payload) => request.post('/enterprise/schedules', payload)
export const deleteSchedule = (id) => request.delete(`/enterprise/schedules/${id}`)
export const changePlan = (plan) => request.put('/enterprise/subscription', { plan })
export const getOperations = () => request.get('/enterprise/operations')
export const getBackups = () => request.get('/enterprise/backups')
export const createBackup = () => request.post('/enterprise/backups')
export const getComments = (resourceType, resourceId) => request.get('/enterprise/comments', { params: { resource_type: resourceType, resource_id: resourceId } })
export const createComment = (payload) => request.post('/enterprise/comments', payload)
export const resolveComment = (id) => request.patch(`/enterprise/comments/${id}/resolve`)
export const getDocumentVersions = (id) => request.get(`/enterprise/documents/${id}/versions`)
export const createDocumentVersion = (id, note = '') => request.post(`/enterprise/documents/${id}/versions`, null, { params: { note } })
